### PR TITLE
Add safe owners to the ScheduledPaymentModuleSetup event

### PR DESCRIPTION
**Pull request by FadhlanR**

### CODE REVIEW

**Review by jurgenwerk — APPROVED** [review]
Thanks! Looks good to me. Once this is merged I'd like to ask to get this deployed to mumbai and goerli asap so I can start the subgraph testing.

**Review by habdelra — APPROVED** [review]
:+1:

**Review by jurgenwerk — CHANGES_REQUESTED** [review]
We noticed with @FadhlanR that this implementation is broken when trying to set up a safe using the `scheduled-payment create-safe` command. 

The error is `Error: {"exception":"CannotEstimateGas: Cannot estimate gas with `eth_estimateGas`: execution reverted: MultiSend should only be called via delegatecall"}`. 

It happens when estimating because it's trying to get the owners of the safe that doesn't exist yet (this is because safe creation is wrapped inside the multi-send transaction).

So the solution we were discussing is to provide the owner in the SDK and pass it as a parameter to the `setUp` function, and not calling the `GnosisSafe(_avatar).getOwners();` in this case. 

There is another case where user brings their own safe and installs the scheduled payment module some other way (not using the SDK). In that case we can use `GnosisSafe(_avatar).getOwners();` because the safe definitely already exists at that point.

**Comment by habdelra** [comment]
that makes sense :+1:

**Review by jurgenwerk — APPROVED** [review]

**Pull request merged**
